set nocompatible
filetype off                   " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'

Bundle 'scrooloose/nerdtree'
Bundle 'altercation/vim-colors-solarized'
Bundle 'rodjek/vim-puppet'
Bundle 'tpope/vim-rails'
Bundle 'moll/vim-bbye'
Bundle 'kien/ctrlp.vim'
Bundle 'tomtom/tcomment_vim'
Bundle 'tpope/vim-fugitive'
Bundle 'bling/vim-airline'

filetype plugin indent on     " required!

set t_Co=256
set background=dark
colorscheme solarized

"set list listchars=tab:⇥⇥,eol:¬ "control char highlighting
set so=14               " keep cursor away from edges of screen
set encoding=utf8       " obviously.
set scrolloff=3         " keep 3 lines when scrolling
set ai                  " set auto-indenting on for programming
syntax on

set showcmd             " display incomplete commands
set nobackup            " do not keep a backup file
set number              " show line numbers
set ruler               " show the current row and column
set cursorline          " highlight current line

set hlsearch            " highlight searches
set incsearch           " do incremental searching
set showmatch           " jump to matches when entering regexp
set ignorecase          " ignore case when searching
set smartcase           " no ignorecase if Uppercase char present
nnoremap <CR> :noh<CR><CR>

set visualbell t_vb=    " turn off error beep/flash
set novisualbell        " turn off visual bell
set noswapfile          " no swapfiles for me

set backspace=indent,eol,start  " make that backspace key work the way it should

" Convert tabs to spaces
set shiftwidth=2
set softtabstop=2
set smarttab
set expandtab

set foldmethod=marker
set laststatus=2
let g:airline_theme="base16"
let g:airline_left_sep = '▶'
let g:airline_right_sep = '◀'
let g:airline_symbols = {}
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
 
" disable arrow keys
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
autocmd Filetype gitcommit setlocal spell textwidth=72

