#!/bin/sh

gnome-keyring-daemon -d

syndaemon -d -t -i 5.0

nitrogen --restore &

$HOME/.dropbox-dist/dropboxd &
trayer --edge bottom --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --height 18 --transparent true --tint 0x000000 &

if [ -z "$(pgrep nm-applet)" ] ; then
    nm-applet --sm-disable &
fi

xscreensaver -no-splash &

xautolock -time 15 -locker "/home/vamsee/.xmonad/suspend" &
chromium-browser &

xmodmap ~/.Xmodmap &

exec dbus-launch --sh-syntax --exit-with-session /home/vamsee/.cabal/bin/xmonad
